spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/template?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  mail:
    host: smtp
    username: your@eamil
    password: email=smtp=pwd
    port: 465
    properties:
      from: your@eamil
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
